### ISSUE TITLE
crashes the app when try to install it or run it

### ISSUE THREAD

**Issue by MrSagarShah** [plivo/plivo-ios-quickstart-app#6]
dyld: Library not loaded: @rpath/PlivoVoiceKit.framework/PlivoVoiceKit
  Referenced from: /private/var/containers/Bundle/Application/BF53A7B4-ACB5-41F0-A8DB-7107A56FCC68/plivoIosQuickstartApp.app/plivoIosQuickstartApp
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
Message from debugger: Terminated due to signal 6

**Comment by eniyavan-muruganantham-plivo** [comment]
@MrSagarShah Can you raise a ticket to support@plivo.com?
